feat: Add network usage monitoring for macOS and Linux
elC0mpa/netstats pull request #1
Opened 2024-11-11 23:08 UTC by evert-arias

Changes:
- [feat: Add network usage monitoring for macOS and Linux](https://github.com/elC0mpa/netstats/commit/67b0aa4e605fe3e2ced1c18357fc340712943433)
- [feat: Update Git tag naming convention in GitHub Actions workflow](https://github.com/elC0mpa/netstats/commit/57074c45a8d046e90e4a56a5ad83fb481af2edaa)

2024-11-11 23:22 UTC, elC0mpa requested changes

2024-11-11 23:22 UTC, elC0mpa commented on linux.go
Please create a folder called Linux
Inside it create a file called core or something you think would be a good name for this file

The package must be the name of the folder, so Linux in this case

The you could import this module from main module

Do the same with the other files please

I am impressed with this PR

2024-11-11 23:26 UTC, evert-arias commented on linux.go
@elC0mpa Thank you for the feedback! I'll implement the recommended changes and update the PR shortly.

2024-11-12 00:29 UTC, elC0mpa commented
Outstanding work @evert-arias

2024-11-12 00:29 UTC, merged